### ISSUE TITLE
Change title of changelog

### ISSUE THREAD

**Issue by naerion89** [semantic-release/changelog#13]
I use semantic release with differents tag format but the changelog version still X.Y.Z version.

I create two tag sprint0-1.0.0 and sprint0-1.0.1 but the version is changelog are 1.0.0 and 1.01.

Ex : 
![image](https://user-images.githubusercontent.com/30294729/36717764-a4f20e38-1b9f-11e8-906f-d14ac7037d07.png)

I wouldlike to display the name of the tag in the changelog.

Regards,
Gaetan

**Comment by pvdlg** [comment]
The changelog is generated with [conventional-changelog-angular](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular).

The information passed to `conventional-changelog-angular` are set [here](https://github.com/semantic-release/release-notes-generator/blob/master/index.js#L40).

If you want to change the output of the release note generator you will have to implement a conventional-changelog with a different template and set it with the [preset option](https://github.com/semantic-release/release-notes-generator#options).

**Comment by pvdlg** [comment]
@naerion89 does that answer your question? Do you need more info on how to implement you own conventional-changelog preset?

**Comment by pvdlg** [comment]
@naerion89 I'm closing the issue as no response has been provided.
