### ISSUE TITLE
Publish a new release with updated version of semantic-release

### ISSUE THREAD

**Issue by ocofaigh** [semantic-release/changelog#244]
The latest release (v6.0.1) is being flagged as vulnerable because it is locked into `"semantic-release": "18.0.0"` which has a known vulnerability in it -> https://github.ibm.com/advisories/GHSA-x2pg-mjhr-2m5x

It looks like the package.json in master branch has already been updated to `"semantic-release": "19.0.3",` however there has been no release yet with this version in it. Could you please trigger a new release?

**Comment by ocofaigh** [comment]
I actually think the vulnerability flagging is coming from the peer dependency:
```
"peerDependencies": {
        "semantic-release": ">=18.0.0"
      }
```

**Comment by travi** [comment]
The defined range already supports what you are asking for. You simply need to update your lockfile or execute with npx instead of declaring it as a dependency

**Comment by ocofaigh** [comment]
Turns out the package-lock.json had a reference to `"semantic-release": "19.0.2"` so after running `npm audit fix` the security warning went away. Closing this.

**Comment by travi** [comment]
Thank you for following up and closing. In the future, please start with a discussion and confirm agreement from maintainers before opening a separate issue for each plugin
