### ISSUE TITLE
Packages with namespace are linked incorrectly

### ISSUE THREAD

**Issue by azdanov** [semantic-release/changelog#44]
Changelog that is generated includes incorrect links.

For example `@mdi/js` get tagged as `@mdi`: https://github.com/azdanov/azdanov.github.io/blob/3ddba4a80370e399045e37b11c9fbbe0b8f3a87d/CHANGELOG.md

Please have a look at this thread https://github.com/azdanov/azdanov.github.io/commit/3ddba4a80370e399045e37b11c9fbbe0b8f3a87d#commitcomment-32474344

**Comment by mdi** [comment]
Not knowing which repo to add the issue to, I also added an issue to renovate https://github.com/renovatebot/renovate/issues/3269

**Comment by pvdlg** [comment]
The change logs are generated by [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog). It seems `conventional-changelog` parses incorrectly and determine your org as a GitHub username.
It should recognize usernames only if they contains valid GitHub username characters: `@mdijs` should be parsed as a username while `@mdi/js` should not.

You should open the issue in the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) repo.

**Comment by azdanov** [comment]
@pvdlg Thanks! I've opened an issue.
