### ISSUE TITLE
FEATURE: Add other formats than Markdown

### ISSUE THREAD

**Issue by DanielHabenicht** [semantic-release/changelog#53]
First, thanks for providing such an awesome plugin. 

Would it be a good idea to provide support for other formats such as HTML? 

The Use Case would be to directly incorporate the file into the app. 

Should this be realised as an extra `changelog-html` plugin or as an option in this plugin? E.g: 

```
{
    "path": "@semantic-release/changelog",
    "changelogFile": "src/changelog.md",
    "format": "html"  // Default value would be "markdown"
},
```

**Comment by pvdlg** [comment]
The content of the release note is generated by https://github.com/semantic-release/release-notes-generator which uses [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog).

You can use the `preset` option to use a different [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) preset.
There is no preset that generate html in the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) repo but you can create your own.

**Comment by NitroBAY** [comment]
For the record, one can also use a popular paser such as markdown it (https://www.npmjs.com/package/markdown-it)

**Comment by DanielHabenicht** [comment]
@pvdlg ok, so the changelog plugin is only for writing the changelog to a file? (Ignoring any language and just appending whatever is in notes, right?)

**Comment by pvdlg** [comment]
> @pvdlg ok, so the changelog plugin is only for writing the changelog to a file? (Ignoring any language and just appending whatever is in notes, right?)

Yes.

> If so, then the changelogTitle attribute is kind of out of place, because if I would change the notes (to HTML) in the step before I couldn`t use the changelog plugin for writing the changelog, which makes it non-versatile.

Yes. Probably other format were not considered when `changelogTitle` was added. See https://github.com/semantic-release/changelog/pull/24 for the context of the `changelogTitle` option.

Feel free to propose a solution that would solve both your use case and what was reported in https://github.com/semantic-release/changelog/issues/21.
