### ISSUE TITLE
Working with @semantic-release/github ?

### ISSUE THREAD

**Issue by jy95** [semantic-release/changelog#6]
Hello,

I use this [config ](https://github.com/jy95/torrent-files-library/blob/master/config/release.config.js) and no changelog were created on my repo for my latest release (v1.2.3). Here is the [build](https://travis-ci.org/jy95/torrent-files-library/jobs/331501875). Do you have any idea why ? Thanks for help

```js
/* eslint-disable no-useless-escape */
module.exports = {
  analyzeCommits: {
    preset: 'eslint',
    releaseRules: './config/release-rules.js',
    parserOpts: {
      headerPattern: /^(?::([\w-]*):)?\s*(\w*):\s*(.*)$/,
      headerCorrespondence: [
        'emoji',
        'tag',
        'message',
      ],
    },
  },
  generateNotes: {
    preset: 'eslint',
    parserOpts: {
      headerPattern: /^(?::([\w-]*):)?\s*(\w*):\s*(.*)$/,
      headerCorrespondence: [
        'emoji',
        'tag',
        'message',
      ],
    },
  },
  release: {
    // eslint-disable-next-line max-len
    verifyConditions: ['@semantic-release/changelog', '@semantic-release/npm', '@semantic-release/github'],
    // eslint-disable-next-line max-len
    publish: ['@semantic-release/changelog', '@semantic-release/npm', '@semantic-release/github'],
  },
};
```

**Comment by pvdlg** [comment]
If you want to commit and push the `CHANGELOG.md` file to your repo you have to use the [git plugin](https://github.com/semantic-release/git). You can find all details in [git#usage](https://github.com/semantic-release/git#usage) documentation.

The `@semantic-release/github` create a GitHub release that includes the changelog text in the description of the release. It doesn't do anything with the `CHANGELOG.md` file.

For support questions, I invite you to use [stackoverflow](https://stackoverflow.com/questions/tagged/semantic-release) or the [Gitter chat](https://gitter.im/semantic-release/semantic-release) as mentioned in the [README](https://github.com/semantic-release/semantic-release#get-help) and [CONTRIBUTING.md#using-the-issue-tracker](https://github.com/semantic-release/semantic-release/blob/caribou/CONTRIBUTING.md#using-the-issue-tracker)

**Comment by jy95** [comment]
Thanks for answer. The confusion is maybe due to the usage part :

> It's **recommended** to use this plugin with the git plugin, so the changelog file will be committed to the Git repository and available on subsequent builds in order to be updated.
> 
> When using with the npm plugin and/or the git plugin the changelog plugin must be called first in order to create or update the changelog file, so it can be included in the npm package and committed to the Git repository.

The word **recommended** is maybe not the best word to express the necessary to have it ...
