### ISSUE TITLE
feature request - dedupe prelease release notes

### ISSUE THREAD

**Issue by mikecbrant** [semantic-release/changelog#62]
When using prerelease functionality, release notes are added to the changelog both for prerelease branch and the master branch (once merged).  This could be considered undesirable for use cases where prerelease is being heavily used, as the resulting changelog can become very noisy.

proposed acceptance criteria:

- when performing changelog modification, logic should be added to deduplicate release note entries in the changelog file. A potential algorithm for doing this is shown below.
- deduplication should be configurable (on/off as a minimum)

potential algorithm:

1. Determine if changelog file exists (as currently done).  If file exists continue. If not, write new file with new release as currently done and end.
2. If dedupe config is not set to `true` execute changelog logic as currently done and end.
3. Evaluate current branch being used for deployment.
4. If master, remove content from top of changelog file to the top of the last master release note heading (i.e. delete release-notes associated with non-master release tags). Continue to step 6
5. If non-master (any other branch for which `prerelease: true` is set in release config), remove content from top of changelog file until most recent release note for either master tag or the specific tag related to this branch is encountered.  This would have the effect of allowing deduplication of release notes merged from other prerelease branches introduced currently releasing branch via merge - with the merged prerelease notes now showing as release notes for the prerelease branch being released.
6. Add current release notes as generated from release note step.
7. Add changelog title line to top of file.
8. End.

Related:

similar request but would turn off changelog activity for prerelease branches, which may not be desirable - #51 

some related background discussion on prerelease changelog behavior - https://github.com/semantic-release/semantic-release/issues/1204

**Comment by pvdlg** [comment]
Altering a release note after the fact is not something desirable.
A release is immutable and changing the changelog after the fact would end up in an erroneous changelog.

Once the commits that were part of a prerelease are merged and published as part of a regular release, the pre-release doesn't cease to exists and some users might continue to use it.

When looking at the altered changelog, there would be no way to know what happened and what was actually release in that pre-release. Changelog are used to know the history of a project and to know what changed when. Altering changelogs file defeat the purpose of having a changelog in the first place.

In addition editing a changelog in automated way is nearly impossible as there is no real standard formatting for changelog and the one that exists are not parsable. Moreover the format of the changelog is completely customizable via conventionnal-changelog presets.

**Comment by DiegoRBaquero** [comment]
I have the same request :/
