### ISSUE TITLE
Preview/Regenerate changelog

### ISSUE THREAD

**Issue by agosto-calvinbehling** [semantic-release/changelog#80]
How would I generate a changelog file without running a release? It seems that `semantic-release --dry-run` causes the changelog to not be generated by skipping the prepare step. Using `semantic-release --no-ci` will add a tag to the repository which is _not an idempotent action_.

Related, how would you generate a changelog for already tagged versions?

``` javascript
{
    "release": {
        "branch": [
            "int"
        ]
    },
    "branches": [
        "int"
    ],
    "plugins": [
        "@semantic-release/release-notes-generator",
        ["@semantic-release/changelog", {
                "changelogFile": "CHANGELOG.md"
        }]
    ]
}
```

**Comment by pvdlg** [comment]
`semantic-release --dry-run` prints the changelog for the new version in the terminal:
![__g___semantic-release](https://user-images.githubusercontent.com/3250552/75398346-700f2b80-58c7-11ea-9bad-e47dc6e2372f.jpg)

semantic-release will create/update the actual `CHANGELOG.md` file via `@semantic-release/changelog` when doing the release.

What would be the point of doing that outside of a release?

**Comment by agosto-calvinbehling** [comment]
I want to have changelogs available as artifacts for PR. Release tagging would not happen until merging to a protected branch which does not allow history modifications and wouldn't create tag conflicts.
I'm also unsure what to do about re-running builds. For example tagging occurs before artifact (changelog) generation and if artifact upload fails then I have a failed build which tagged my repository. Re-running the build won't regenerate the artifacts because the tag already exists. This forces manual intervention to either delete the tags or keep pushing releases until one succeeds.

**Comment by agosto-calvinbehling** [comment]
Another note is that the date in the changelog is based on execution date. This means changelog generation create a non-reproducible artifact. I.E. If I create a release, and then tomorrow regenerate the changelog (since the tooling doesn't currently allow this, that means deleting the tags and re-releasing), you would arguably have the _same release_ with a _different date_. Since you reverted annotated tagging, you could use the date of the commit referenced by the tag instead of "today".

More info on why you might care can be found here: https://reproducible-builds.org/

**Comment by pvdlg** [comment]
> Release tagging would not happen until merging to a protected branch which does not allow history modifications and wouldn't create tag conflicts.

The solution is to allow the user that run semantic-release to push a commit on that branch on a release. semantic-release doesn't run on PRs for several reasons. One of them is that secret variable are not available on CIs when running from a forked repo for security reasons. So we can't interact with the remote on a PR build. 

> For example tagging occurs before artifact (changelog) generation and if artifact upload fails then I have a failed build which tagged my repository.

No, if you configure seamtnic-release per the documentation, the changelog should be created and committed to the remote before tagging.

> Re-running the build won't regenerate the artifacts because the tag already exists. This forces manual intervention to either delete the tags or keep pushing releases until one succeeds.

That's a (rare) know issue: https://github.com/semantic-release/semantic-release/issues/896

> Another note is that the date in the changelog is based on execution date. This means changelog generation creates a non-reproducible artifact. I.E. If I create a release, and then tomorrow regenerate the changelog (since the tooling doesn't currently allow this, that means deleting the tags and re-releasing), you would arguably have the same release with a different date. 

semantic-release is a release tool not a build tool. You want you build to be reproductible but not your releases. A release should be idempotent. You don't want to publish artifacts with the same version multiple time that might correspond to a different codebase or build environment.
