### ISSUE TITLE
generated changelog.md doesn't pass linting

### ISSUE THREAD

**Issue by amclin** [semantic-release/changelog#84]
[`remark-lint`](https://www.npmjs.com/package/remark-lint) reports several styling issues with the markdown generated by `@semantic-release/changelog`

Examples:
```
            8:3  warning  Incorrect list-item indent: add 2 spaces  list-item-indent            remark-lint
      8:13-8:23  warning  Use the trailing `[]` on reference links  no-shortcut-reference-link  remark-lint
      8:13-8:23  warning  Found reference to undefined definition   no-undefined-references     remark-lint
            9:3  warning  Incorrect list-item indent: add 2 spaces  list-item-indent            remark-lint
           10:3  warning  Incorrect list-item indent: add 2 spaces  list-item-indent            remark-lint
           17:3  warning  Incorrect list-item indent: add 2 spaces  list-item-indent            remark-lint
           18:3  warning  Incorrect list-item indent: add 2 spaces  list-item-indent            remark-lint
```

Are there any plans for `semantic-release/changelog` to conform to an established linting pattern for markdown?

Alternatively, can the syntax be made configurable in some way so consumers can configure linting compliant patterns for their projects? I hate encouraging teams to exclude files from automated checks.

**Comment by pvdlg** [comment]
The content of the Changelog is generated by https://github.com/semantic-release/release-notes-generator which uses https://github.com/conventional-changelog/conventional-changelog.

I would recommend to open an issue with https://github.com/conventional-changelog/conventional-changelog

You can customize the format of the output by creating your own conventional-changelog preset and configure it with the [preset option](https://github.com/semantic-release/release-notes-generator#options)

**Comment by amclin** [comment]
Thanks for the suggestion, I followed up with the conventional-changelog project
