### ISSUE TITLE
[Help] Change log not written

### ISSUE THREAD

**Issue by raulfdm** [semantic-release/changelog#87]
Hello.

I'm seeing this is a recurring problem here but I couldn't find a reason for that.

I have a open-source project which I add in this pr https://github.com/raulfdm/pin-dependencies-checker/pull/3 the change log plugin.

I notice that no commit with the updated CHANGELOG was made. Do I need any other setup? :S

Thanks in advance.

**Comment by abdelrahmanahmed** [comment]
Hi @raulfdm , what i can see from your [releaserc file](https://github.com/raulfdm/pin-dependencies-checker/blob/master/.releaserc.js) that you are forgot to add [git plugin](https://github.com/semantic-release/git). This plugin is need to add a new commit to your repo. Modify your `releaserc` file to be like this:
```javascript
module.exports = {
  branches: ['master'],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/npm',
    '@semantic-release/github',
    '@semantic-release/git'
  ],
};
```

**Comment by raulfdm** [comment]
I did that and indeed solves the problem. Thanks @abdelrahmanahmed
